// This file is auto-generated by scripts/generate-manifest.js
// Do not modify this file directly.

import type { WizardManifest } from './src/types/wizard';

export const wizardManifest: WizardManifest = {
  "components": [],
  "layouts": [],
  "utils": [],
  "hooks": [],
  "data": []
} as const;