// ⚠️ AUTO-GENERATED by scripts/generate-registry.js
// Do not edit manually.
import React from 'react';
import { Suggestion } from './blocks/ai/Actions';
import { Actions } from './blocks/ai/Actions';
import { ChatFAB } from './blocks/ai/ChatFAB';
import { Conversation } from './blocks/ai/Conversation';
import { Loader } from './blocks/ai/Loader';
import { Message } from './blocks/ai/Message';
import { PromptInput } from './blocks/ai/PromptInput';
import { DeviceCard } from './blocks/iot/DeviceCard';
import { ActivityFeed } from './components/data-display/ActivityFeed';
import { BarChart } from './components/data-display/BarChart';
import { ChartWithTable } from './components/data-display/ChartWithTable';
import { CodeBlock } from './components/data-display/CodeBlock';
import { DataTable } from './components/data-display/DataTable';
import { LineChart } from './components/data-display/LineChart';
import { PieChart } from './components/data-display/PieChart';
import { StatCard } from './components/data-display/StatCard';
import { StatusBadge } from './components/data-display/StatusBadge';
import { Table } from './components/data-display/Table';
import { Alert } from './components/feedback/Alert';
import { EmptyState } from './components/feedback/EmptyState';
import { TippyTooltip } from './components/feedback/TippyTooltip';
import { Toast } from './components/feedback/Toast';
import { ToastProvider } from './components/feedback/ToastProvider';
import { ButtonGroup } from './components/forms/ButtonGroup';
import { Checkbox } from './components/forms/Checkbox';
import { ComboBox } from './components/forms/ComboBox';
import { DatePicker } from './components/forms/DatePicker';
import { FileUpload } from './components/forms/FileUpload';
import { FormTemplate } from './components/forms/FormTemplate';
import { Input } from './components/forms/Input';
import { Radio } from './components/forms/Radio';
import { SearchInput } from './components/forms/SearchInput';
import { SegmentedControl } from './components/forms/SegmentedControl';
import { Textarea } from './components/forms/Textarea';
import { ToggleSwitch } from './components/forms/ToggleSwitch';
import { AccordionItem } from './components/layout/Accordion';
import { Accordion } from './components/layout/Accordion';
import { ActionBar } from './components/layout/ActionBar';
import { Card } from './components/layout/Card';
import { Drawer } from './components/layout/Drawer';
import { ListItem } from './components/layout/List';
import { List } from './components/layout/List';
import { DefinitionTerm } from './components/layout/List';
import { DefinitionDescription } from './components/layout/List';
import { DefinitionList } from './components/layout/List';
import { Modal } from './components/layout/Modal';
import { PageHeader } from './components/layout/PageHeader';
import { SectionHeader } from './components/layout/SectionHeader';
import { Sidebar } from './components/layout/Sidebar';
import { BreadcrumbItem } from './components/navigation/Breadcrumbs';
import { Breadcrumbs } from './components/navigation/Breadcrumbs';
import { MenuDivider } from './components/navigation/Menu';
import { MenuItem } from './components/navigation/Menu';
import { Menu } from './components/navigation/Menu';
import { Pagination } from './components/navigation/Pagination';
import { Stepper } from './components/navigation/Stepper';
import { TabPanel } from './components/navigation/Tabs';
import { Tabs } from './components/navigation/Tabs';
import { Avatar } from './components/ui/Avatar';
import { Badge } from './components/ui/Badge';
import { Button } from './components/ui/Button';
import { Icon } from './components/ui/Icon';

export const AUTO_REGISTRY: Record<string, React.FC<any>> = {
  'Suggestion': Suggestion,
  'suggestion': Suggestion,
  'Actions': Actions,
  'actions': Actions,
  'ChatFAB': ChatFAB,
  'chat-fab': ChatFAB,
  'chatfab': ChatFAB,
  'Conversation': Conversation,
  'conversation': Conversation,
  'Loader': Loader,
  'loader': Loader,
  'Message': Message,
  'message': Message,
  'PromptInput': PromptInput,
  'prompt-input': PromptInput,
  'promptinput': PromptInput,
  'DeviceCard': DeviceCard,
  'device-card': DeviceCard,
  'devicecard': DeviceCard,
  'ActivityFeed': ActivityFeed,
  'activity-feed': ActivityFeed,
  'activityfeed': ActivityFeed,
  'BarChart': BarChart,
  'bar-chart': BarChart,
  'barchart': BarChart,
  'ChartWithTable': ChartWithTable,
  'chart-with-table': ChartWithTable,
  'chartwithtable': ChartWithTable,
  'CodeBlock': CodeBlock,
  'code-block': CodeBlock,
  'codeblock': CodeBlock,
  'DataTable': DataTable,
  'data-table': DataTable,
  'datatable': DataTable,
  'LineChart': LineChart,
  'line-chart': LineChart,
  'linechart': LineChart,
  'PieChart': PieChart,
  'pie-chart': PieChart,
  'piechart': PieChart,
  'StatCard': StatCard,
  'stat-card': StatCard,
  'statcard': StatCard,
  'StatusBadge': StatusBadge,
  'status-badge': StatusBadge,
  'statusbadge': StatusBadge,
  'Table': Table,
  'table': Table,
  'Alert': Alert,
  'alert': Alert,
  'EmptyState': EmptyState,
  'empty-state': EmptyState,
  'emptystate': EmptyState,
  'TippyTooltip': TippyTooltip,
  'tippy-tooltip': TippyTooltip,
  'tippytooltip': TippyTooltip,
  'Toast': Toast,
  'toast': Toast,
  'ToastProvider': ToastProvider,
  'toast-provider': ToastProvider,
  'toastprovider': ToastProvider,
  'ButtonGroup': ButtonGroup,
  'button-group': ButtonGroup,
  'buttongroup': ButtonGroup,
  'Checkbox': Checkbox,
  'checkbox': Checkbox,
  'ComboBox': ComboBox,
  'combo-box': ComboBox,
  'combobox': ComboBox,
  'DatePicker': DatePicker,
  'date-picker': DatePicker,
  'datepicker': DatePicker,
  'FileUpload': FileUpload,
  'file-upload': FileUpload,
  'fileupload': FileUpload,
  'FormTemplate': FormTemplate,
  'form-template': FormTemplate,
  'formtemplate': FormTemplate,
  'Input': Input,
  'input': Input,
  'Radio': Radio,
  'radio': Radio,
  'SearchInput': SearchInput,
  'search-input': SearchInput,
  'searchinput': SearchInput,
  'SegmentedControl': SegmentedControl,
  'segmented-control': SegmentedControl,
  'segmentedcontrol': SegmentedControl,
  'Textarea': Textarea,
  'textarea': Textarea,
  'ToggleSwitch': ToggleSwitch,
  'toggle-switch': ToggleSwitch,
  'toggleswitch': ToggleSwitch,
  'AccordionItem': AccordionItem,
  'accordion-item': AccordionItem,
  'accordionitem': AccordionItem,
  'Accordion': Accordion,
  'accordion': Accordion,
  'ActionBar': ActionBar,
  'action-bar': ActionBar,
  'actionbar': ActionBar,
  'Card': Card,
  'card': Card,
  'Drawer': Drawer,
  'drawer': Drawer,
  'ListItem': ListItem,
  'list-item': ListItem,
  'listitem': ListItem,
  'List': List,
  'list': List,
  'DefinitionTerm': DefinitionTerm,
  'definition-term': DefinitionTerm,
  'definitionterm': DefinitionTerm,
  'DefinitionDescription': DefinitionDescription,
  'definition-description': DefinitionDescription,
  'definitiondescription': DefinitionDescription,
  'DefinitionList': DefinitionList,
  'definition-list': DefinitionList,
  'definitionlist': DefinitionList,
  'Modal': Modal,
  'modal': Modal,
  'PageHeader': PageHeader,
  'page-header': PageHeader,
  'pageheader': PageHeader,
  'SectionHeader': SectionHeader,
  'section-header': SectionHeader,
  'sectionheader': SectionHeader,
  'Sidebar': Sidebar,
  'sidebar': Sidebar,
  'BreadcrumbItem': BreadcrumbItem,
  'breadcrumb-item': BreadcrumbItem,
  'breadcrumbitem': BreadcrumbItem,
  'Breadcrumbs': Breadcrumbs,
  'breadcrumbs': Breadcrumbs,
  'MenuDivider': MenuDivider,
  'menu-divider': MenuDivider,
  'menudivider': MenuDivider,
  'MenuItem': MenuItem,
  'menu-item': MenuItem,
  'menuitem': MenuItem,
  'Menu': Menu,
  'menu': Menu,
  'Pagination': Pagination,
  'pagination': Pagination,
  'Stepper': Stepper,
  'stepper': Stepper,
  'TabPanel': TabPanel,
  'tab-panel': TabPanel,
  'tabpanel': TabPanel,
  'Tabs': Tabs,
  'tabs': Tabs,
  'Avatar': Avatar,
  'avatar': Avatar,
  'Badge': Badge,
  'badge': Badge,
  'Button': Button,
  'button': Button,
  'Icon': Icon,
  'icon': Icon,
};
